# -*- coding: utf-8 -*-
"""Def_Reto5NayidG_26.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bp1terJIvHmml84Q6nSlkWsjOQLjOZ_d
"""

#borrador2_5,  NAYID_G26
print("*********************************************")
print("**Reto 5 Nayid Douvan Corredor Castillo G26**")
print("*********************************************")


def pedirDatos(N): # Ejemplo 
  dataProd = ('Código', 'Nombre', 'Cantidad', 'Valor unitario', 'Tipo de IVA')
  list_dataProd = []
  compra = {}
 
  for item in range(N):
    list_dataProd = []
    for dato in dataProd:
      list_dataProd.append(input(f"Digite el {dato} del producto {item + 1}: "))


      compra[item+1] = list_dataProd
       
  return compra  
# FIN FUNCION PEDIR DATOS

# FUNCION PROCESAR DATOS - RECIBE PARAMETROS (DICCIONARIO, N), NO RETORNA SINO QUE LLAMA LA FUNCION IMPRIMIR
 
def procesarDatos (compra,N):
   iva = (0, 0.05, 0.19)
   acusubTotal = 0 
   acuIva = 0 
   acuTotalProd = 0 
   for item in range(N):
     
    compra[item+1].append(int(compra[item+1][2]) * int(compra[item+1][3]))
    compra[item+1].append(float(iva[int(compra[item+1][4])-1]) * int(compra[item+1][5]))
    compra[item+1].append(int(compra[item+1][5]) + int(compra[item+1][6]))

    acusubTotal += compra[item+1][5]
    acuIva += compra[item+1][6]
    acuTotalProd += compra[item+1][7]  

   imp(N, compra, acusubTotal, acuIva, acuTotalProd, item)

def imp(N, compra, acusubTotal, acuIva, acuTotalProd, item):
  for i in range(N):
    print(f"Codigo del Producto {i + 1}: ", compra[item+1][0])
    print(f"listanomProducto {i + 1}: ", compra[item+1][1])
    print(f"listacanProducto {i + 1}: ", compra[item+1][2])
    print(f"listavalUnitario {i + 1}: ", compra[item+1][3])
    print(f"listatipoIva {i + 1}: ", compra[item+1][4])
    print(f"listasubtTotal {i + 1}: ", compra[item+1][5])
    print(f"listaIva {i + 1}: ", compra[item+1][6])
    print(f"listatotalProducto {i + 1}: ", compra[item+1][7])
    

  print("********************************")
  print("Totales de la compra: ")
  print("********************************")
  print("SubTotal de la compra: ", acusubTotal)
  print("acumulativo iva de la compra: ", acuIva)
  print("Total de la compra: ", acuTotalProd)

  print(compra)

while True:
  try:
    N = int(input("Digite la cantidad de Artículos a facturar: "))
    break
  except ValueError:
    print("por favor ingrese valores numericos enteros: ")  

dict_compra = pedirDatos(N)
procesarDatos(dict_compra, N)