# -*- coding: utf-8 -*-
"""Reto4_Nayid.def_G26.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cAg4MHIsWm2kpxTuPAvozC5rERgIhoHZ
"""

#RETO_4,  NAYID_G26


acusubTotal = 0
acuIva = 0
acuTotalProd = 0
 
N = int(input("Digite la cantidad de Artículos a facturar: "))
dataProd = ('Código', 'Nombre', 'Cantidad', 'Valor unitario', 'Tipo de IVA')
list_dataProd = []
tipoIva = []
compra = {}
iva = (0, 0.05, 0.19)

for item in range(N):
  list_dataProd = []
  for dato in dataProd:
    list_dataProd.append(input(f"Digite el {dato} del producto {item + 1}: "))

  
  compra[item+1] = list_dataProd

  #neto
  compra[item+1].append(int(compra[item+1][2]) * int(compra[item+1][3]))
  #iva 
  compra[item+1].append(float(iva[int(compra[item+1][4])-1]) * int(compra[item+1][5]))
  #total
  compra[item+1].append(int(compra[item+1][5]) + int(compra[item+1][6]))

  

  print("*********************************")

  acusubTotal += compra[item+1][5]
  acuIva += compra[item+1][6]
  acuTotalProd += compra[item+1][7]


  for i in range(N):
    print(f"Codigo del Producto {i + 1}: ", compra[item+1][0])
    print(f"listanomProducto {i + 1}: ", compra[item+1][1])
    print(f"listacanProducto {i + 1}: ", compra[item+1][2])
    print(f"listavalUnitario {i + 1}: ", compra[item+1][3])
    print(f"listatipoIva {i + 1}: ", compra[item+1][4])
    print(f"listasubtTotal {i + 1}: ", compra[item+1][5])
    print(f"listaIva {i + 1}: ", compra[item+1][6])
    print(f"listatotalProducto {i + 1}: ", compra[item+1][7])
   

print("********************************")
print("Totales de la compra: ")
print("********************************")
print("SubTotal de la compra: ", acusubTotal)
print("acumulativo iva de la compra: ", acuIva)
print("Total de la compra: ", acuTotalProd)

print(compra)

print(compra)